---
name: Merge
"on":
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest

    steps:
      - uses: mheap/github-action-required-labels@132879b972cb7f2ac593006455875098e73cc7f2 # v5.4.0
        with:
          mode: exactly
          count: 0
          labels: "S-do-not-merge, S-wip"
