---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
          - alpine
          - debian
          - ubuntu
        include:
          - build: alpine
            dockerfile: alpine/Dockerfile
          - build: debian
            dockerfile: debian/bullseye/slim/Dockerfile
          - build: ubuntu
            dockerfile: ubuntu/jammy/Dockerfile

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false

  docker:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Lint Ubuntu Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/ubuntu/jammy/Dockerfile

      - name: Lint Debian Slim Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/debian/bullseye/slim/Dockerfile

      - name: Lint Alpine Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/alpine/Dockerfile

  ruby:
    name: Lint and format Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251 # v1.150.0
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Lint and check formatting with Rubocop
        run: bundle exec rubocop --format github

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Format with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict --format github .
          echo "OK"
