---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
          - alpine
          - debian
          - ubuntu
        include:
          - build: alpine
            dockerfile: alpine/Dockerfile
          - build: debian
            dockerfile: debian/bookworm/slim/Dockerfile
          - build: ubuntu
            dockerfile: ubuntu/jammy/Dockerfile

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Build and push Docker images
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6.5.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false

  docker:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Lint Ubuntu Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/ubuntu/jammy/Dockerfile

      - name: Lint Debian Slim Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/debian/bookworm/slim/Dockerfile

      - name: Lint Alpine Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/alpine/Dockerfile

  ruby:
    name: Lint and format Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Lint and check formatting with Rubocop
        run: bundle exec rubocop --format github

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js runtime
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "lts/*"

      - name: Install toolchain
        run: npm ci

      - name: Format with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict --format github .
          echo "OK"
