---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
          - alpine
          - debian
          - ubuntu
        include:
          - build: alpine
            dockerfile: alpine/Dockerfile
          - build: debian
            dockerfile: debian/bookworm/slim/Dockerfile
          - build: ubuntu
            dockerfile: ubuntu/jammy/Dockerfile

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Build and push Docker images
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false

  docker:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Lint Ubuntu Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/ubuntu/jammy/Dockerfile

      - name: Lint Debian Slim Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/debian/bookworm/slim/Dockerfile

      - name: Lint Alpine Dockerfile
        uses: docker://hadolint/hadolint:latest
        with:
          entrypoint: /bin/hadolint
          args: --config /github/workspace/.hadolint.yaml /github/workspace/alpine/Dockerfile

  ruby:
    name: Lint and format Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@1198b074305f9356bd56dd4b311757cc0dab2f1c # v1.175.1
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Lint and check formatting with Rubocop
        run: bundle exec rubocop --format github

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Setup Node.js runtime
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "lts/*"

      - name: Install toolchain
        run: npm ci

      - name: Format with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict --format github .
          echo "OK"
