name: Docker Image CI
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * *" # build nightly!

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu, slim, alpine]

    steps:
      - uses: actions/checkout@v2

      - name: Get Artichoke HEAD commit
        id: trunk
        run: |
          COMMIT_SHA="$(curl https://api.github.com/repos/artichoke/artichoke/commits/master | jq --raw-output '.sha')"
          echo "::set-output name=sha::$COMMIT_SHA"

      - name: Build the Docker image
        run: >-
          docker build .
          --build-arg ARTICHOKE_NIGHTLY_VER=${{ steps.trunk.outputs.sha }}
          --file Dockerfile.${{ matrix.image }}
          --tag artichokeruby/artichoke:${{ matrix.image }}-nightly
          --tag artichokeruby/artichoke:${{ matrix.image }}-nightly-${{ steps.trunk.outputs.sha }}
          --label "org.opencontainers.image.created=$(date --rfc-3339=seconds)"
          --label "org.opencontainers.image.version=${{ steps.trunk.outputs.sha }}"
          --label "org.opencontainers.image.revision=${{ steps.trunk.outputs.sha }}"

      - name: Extra Canonical image tags
        if: matrix.image == 'ubuntu'
        run: |
          docker tag artichokeruby/artichoke:${{ matrix.image }}-nightly artichokeruby/artichoke:latest
          docker tag artichokeruby/artichoke:${{ matrix.image }}-nightly artichokeruby/artichoke:${{ steps.trunk.outputs.sha }}
          docker tag artichokeruby/artichoke:${{ matrix.image }}-nightly artichokeruby/artichoke:${{ matrix.image }}18.04-nightly

      - name: Extra Debian image tags
        if: matrix.image == 'slim'
        run: |
          docker tag artichokeruby/artichoke:${{ matrix.image }}-nightly artichokerb/artichoke:${{ matrix.image }}-buster-nightly

      - name: Extra Alpine image tags
        if: matrix.image == 'alpine'
        run: |
          docker tag artichokeruby/artichoke:${{ matrix.image }}-nightly artichokerb/artichoke:${{ matrix.image }}3-nightly

      - name: Push the Docker image
        if: github.ref == 'refs/heads/trunk'
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_TOKEN"
          docker push artichokeruby/artichoke
