---
name: Docker Image CI (defaults)
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ubuntu/focal/Dockerfile
          push: false

  debian-slim:
    name: Debian Slim
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: debian/bullseye/slim/Dockerfile
          push: false

  alpine:
    name: Alpine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: alpine/Dockerfile
          push: false
