---
name: Docker Image CI (defaults)
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ubuntu/focal/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=docker-defaults-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-v1

  debian-slim:
    name: Debian Slim
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: debian/bullseye/slim/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=docker-defaults-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-v1

  alpine:
    name: Alpine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: alpine/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=docker-defaults-${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-v1
