---
name: Docker Image CI (defaults)
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"

jobs:
  ubuntu-bionic:
    name: Ubuntu 18.04 Bionic
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ubuntu/bionic/Dockerfile
          push: false

  debian-buster-slim:
    name: Debian Buster Slim
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: debian/bullseye/slim/Dockerfile
          push: false

  alpine:
    name: Alpine 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: alpine/Dockerfile
          push: false
